baseurl      = "https://mdvico.github.io/"
title        = "Matías D. Vico's personal site"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 5

archetypeDir = "archetypes"
contentDir   = "content"
dataDir      = "data"
layoutDir    = "layouts"
publishDir   = "public"

enableEmoji  = true

[author]
  name = "Matías Daniel Vico"

[params]
  # Table of Content on the header of each article
  toc = true

  # Show an estimated reading time below the title for every article
  showReadingTime = true

  enable_nested_menu = false

  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "There are things that you don't know that you don't know."

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "My blog"
  keywords = "homepage, blog"
  images = [""]

  enableThemeToggle = false
  defaultTheme = "dark"

  # Social icons
  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/HerrFusion"

  [[params.social]]
    name = "github"
    url  = "https://github.com/mdvico"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/matiasvico"

  [[params.social]]
    name = "stackoverflow"
    url  = "https://stackoverflow.com/users/3173955/mvico"

[taxonomies]
    tag      = "tags"
    category = "categories"

[languages]
  [languages.en]
    title = "Matías Daniel Vico"
    subtitle = "There are things that you don't know that you don't know."
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"
    readMore = "Read more"
    menuMore = "Show more"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    minuteReadingTime = "minutes read"
    writtenBy = "Written by"

    [languages.en.params.logo]
      logoText = "cd ~/projects"
      logoHomeLink = "/"

  [languages.en.menu]
    [[languages.en.menu.main]]
      identifier = "about"
      name       = "About"
      url        = "/posts/my-first-post"
    [[languages.en.menu.main]]
      identifier = "blog"
      name       = "Blog"
      url        = "/posts"
#    [[languages.en.menu.main]]
#      identifier = "cv"
#      name       = "CV"
#    [[languages.en.menu.main]]
#      parent     = "cv" 
#      identifier = "cv-html"
#      name       = "CV [HTML]"
#      url        = "/cv/cv.html"
    [[languages.en.menu.main]]
#      parent     = "cv" 
      identifier = "cv-pdf"
      name       = "CV [PDF]"
      url        = "/cv/cv.pdf"


  [languages.es]
    title = "Matías Daniel Vico"
    subtitle = "Hay cosas que no sabes que no sabes."
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Leer otros posteos"
    readMore = "Leer más"
    menuMore = "Ver más"
    newerPosts = "Posteos nuevos"
    olderPosts = "Posteos viejos"
    minuteReadingTime = "minutos de lectura"
    writtenBy = "Escrito por"

    [languages.es.params]
      homeSubtitle = "Hay cosas que no sabes que no sabes."
    [languages.es.params.logo]
      logoText = "cd ~/proyectos"
      logoHomeLink = "/es"

  [languages.es.menu]
    [[languages.es.menu.main]]
      identifier = "about"
      name       = "Acerca de"
      url        = "/posts/my-first-post"
    [[languages.es.menu.main]]
      identifier = "blog"
      name       = "Blog"
      url        = "/posts"
#    [[languages.es.menu.main]]
#      identifier = "cv"
#      name       = "CV"
#    [[languages.es.menu.main]]
#      identifier = "cv-html"
#      name       = "CV [HTML]"
#      parent     = "cv" 
#      url        = "/cv/cv.html"
    [[languages.es.menu.main]]
      identifier = "cv-pdf"
      name       = "CV [PDF]"
#      parent     = "cv" 
      url        = "/cv/cv.pdf"


[markup]
defaultMarkdownHandler = 'goldmark'
  [markup.tableOfContents]
  endLevel = 2
  ordered = false
  startLevel = 1
