baseurl      = "https://mdvico.github.io"
title        = "Matías D. Vico's personal site"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10

archetypeDir = "archetypes"
contentDir   = "content"
dataDir      = "data"
layoutDir    = "layouts"
publishDir   = "public"

enableEmoji     = true

[author]
  name = "Matías Daniel Vico"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "There are things that you don't know that you don't know."

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "My blog"
  keywords = "homepage, blog"
  images = [""]

  enableThemeToggle = true
  defaultTheme = "dark"

  # Social icons
  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/HerrFusion"

  [[params.social]]
    name = "github"
    url  = "https://github.com/mdvico"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/matiasvico"

  [[params.social]]
    name = "stackoverflow"
    url  = "https://stackoverflow.com/users/3173955/mvico"

[taxonomies]
    category = "categories"
    tag      = "tags"
    series   = "series"

[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/posts/my-first-post"
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"
  [[menu.main]]
    identifier = "cv"
    name       = "CV"
    url        = "/"

[languages]
  [languages.en]
    title = "Matías Daniel Vico"
    subtitle = "There are things that you don't know that you don't know."
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "cd ~/projects"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  [languages.es]
    title = "Matías Daniel Vico"
    subtitle = "Hay cosas que no sabes que no sabes"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"
    [languages.es.params]
      homeSubtitle = "Hay cosas que no sabes que no sabes"
    [languages.es.params.logo]
      logoText = "cd ~/proyectos"
      logoHomeLink = "/"

